### ISSUE TITLE
Security policy link not working

### ISSUE THREAD

**Issue by wfjake** [russellhaering/gosaml2#118]
The link in SECURITY.md is broken, it returns a 404 Not Found when I click the link. I think you may have accidentally disabled private reporting in Settings ([docs](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository)), as I don't see the button present in the Security tab for this repository but can see it on other repositories.

**Comment by russellhaering** [comment]
You're right, good catch - thanks!

Should be fixed now, please re-open if it still doesn't work for you.
