### ISSUE TITLE
Failures on saml.oktadev.com

### ISSUE THREAD

**Issue by russellhaering** [russellhaering/gosaml2#26]
Originally reported at https://github.com/russellhaering/goxmldsig/issues/25

I'm working on improving validation, should have a fix within a few days.

**Comment by russellhaering** [comment]
@arun251 this should be fixed now. I also added a local test suite which simulates the behavior of saml.oktadev.com to make it easier to avoid regressions in the future.

Let me know if you see any other issues.

**Comment by arun251** [comment]
Very cool, thanks!
