### ISSUE TITLE
Add proper documentation on different functions available 

### ISSUE THREAD

**Issue by Swechhya** [russellhaering/gosaml2#87]
Thank you for this package. 

I was using this package and realized that it lacked proper documentation. For a start, there could at least be a list of functions in the package. I had to dig through the code to find the functions that I wanted to use. It would be really helpful to have a list of functions available in README.

Having an example of the implementation of each of the functions would immensely help developers who use this package.

**Comment by moorereason** [comment]
There's a button at the top of the README to the godocs:  https://pkg.go.dev/github.com/russellhaering/gosaml2
