### ISSUE TITLE
Decrypt assertion returns wrong error value

### ISSUE THREAD

**Issue by sbapu-arista** [russellhaering/gosaml2#94]
In decode_response.go post decryption if there is an error in deflating the xml post decryption then the handler returns the error from decryption which will always be nil. It should return the error in parsing the decrypted XML

		raw, derr := encryptedAssertion.DecryptBytes(decryptCert)
		if derr != nil {
			return fmt.Errorf("unable to decrypt encrypted assertion: %v", derr)
		}

		doc, _, err := parseResponse(raw)
		if err != nil {
			return fmt.Errorf("unable to create element from decrypted assertion bytes: %v", derr)
		}
After parseResponse, it returns derr which will always be nil whereas it should be returning err. Is this a wrong expectation or am I missing something here?

**Comment by russellhaering** [comment]
Fixed in #95 and released in v0.8.1 - thanks for reporting!
